export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          password_hash: string | null;
          full_name: string;
          avatar_url: string | null;
          phone: string | null;
          google_id: string | null;
          supabase_id: string | null;
          email_verified: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          password_hash?: string | null;
          full_name: string;
          avatar_url?: string | null;
          phone?: string | null;
          google_id?: string | null;
          supabase_id?: string | null;
          email_verified?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          password_hash?: string | null;
          full_name?: string;
          avatar_url?: string | null;
          phone?: string | null;
          google_id?: string | null;
          supabase_id?: string | null;
          email_verified?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          owner_id: string;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          owner_id: string;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          owner_id?: string;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: string;
          joined_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role?: string;
          joined_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role?: string;
          joined_at?: string;
        };
      };
      property_listings: {
        Row: {
          id: string;
          organization_id: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          zip_code: string | null;
          neighborhood: string | null;
          listing_status: string;
          listing_price: number | null;
          bedrooms: number | null;
          bathrooms: number | null;
          square_feet: number | null;
          lot_size: string | null;
          year_built: number | null;
          property_type: string | null;
          features: string[] | null;
          mls_number: string | null;
          target_audience: string | null;
          positioning_notes: string | null;
          open_house_date: string | null;
          open_house_start: string | null;
          open_house_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          zip_code?: string | null;
          neighborhood?: string | null;
          listing_status?: string;
          listing_price?: number | null;
          bedrooms?: number | null;
          bathrooms?: number | null;
          square_feet?: number | null;
          lot_size?: string | null;
          year_built?: number | null;
          property_type?: string | null;
          features?: string[] | null;
          mls_number?: string | null;
          target_audience?: string | null;
          positioning_notes?: string | null;
          open_house_date?: string | null;
          open_house_start?: string | null;
          open_house_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          zip_code?: string | null;
          neighborhood?: string | null;
          listing_status?: string;
          listing_price?: number | null;
          bedrooms?: number | null;
          bathrooms?: number | null;
          square_feet?: number | null;
          lot_size?: string | null;
          year_built?: number | null;
          property_type?: string | null;
          features?: string[] | null;
          mls_number?: string | null;
          target_audience?: string | null;
          positioning_notes?: string | null;
          open_house_date?: string | null;
          open_house_start?: string | null;
          open_house_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      brand_kits: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          is_default: boolean;
          agent_name: string | null;
          agent_title: string | null;
          agent_phone: string | null;
          agent_email: string | null;
          brokerage_name: string | null;
          license_number: string | null;
          logo_url: string | null;
          headshot_url: string | null;
          primary_color: string;
          secondary_color: string;
          accent_color: string;
          font_primary: string;
          font_secondary: string;
          social_links: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          is_default?: boolean;
          agent_name?: string | null;
          agent_title?: string | null;
          agent_phone?: string | null;
          agent_email?: string | null;
          brokerage_name?: string | null;
          license_number?: string | null;
          logo_url?: string | null;
          headshot_url?: string | null;
          primary_color?: string;
          secondary_color?: string;
          accent_color?: string;
          font_primary?: string;
          font_secondary?: string;
          social_links?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          is_default?: boolean;
          agent_name?: string | null;
          agent_title?: string | null;
          agent_phone?: string | null;
          agent_email?: string | null;
          brokerage_name?: string | null;
          license_number?: string | null;
          logo_url?: string | null;
          headshot_url?: string | null;
          primary_color?: string;
          secondary_color?: string;
          accent_color?: string;
          font_primary?: string;
          font_secondary?: string;
          social_links?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          organization_id: string;
          created_by_id: string;
          property_id: string | null;
          brand_kit_id: string | null;
          title: string;
          type: string;
          status: string;
          style_settings: Json;
          voice_settings: Json;
          infographic_settings: Json;
          generated_script: Json | null;
          generated_caption: string | null;
          generated_hashtags: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_id: string;
          property_id?: string | null;
          brand_kit_id?: string | null;
          title: string;
          type: string;
          status?: string;
          style_settings?: Json;
          voice_settings?: Json;
          infographic_settings?: Json;
          generated_script?: Json | null;
          generated_caption?: string | null;
          generated_hashtags?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_id?: string;
          property_id?: string | null;
          brand_kit_id?: string | null;
          title?: string;
          type?: string;
          status?: string;
          style_settings?: Json;
          voice_settings?: Json;
          infographic_settings?: Json;
          generated_script?: Json | null;
          generated_caption?: string | null;
          generated_hashtags?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          organization_id: string;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          plan_name: string;
          video_renders_limit: number | null;
          video_renders_used: number;
          storage_limit_gb: number | null;
          storage_used_bytes: number;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          trial_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_name: string;
          video_renders_limit?: number | null;
          video_renders_used?: number;
          storage_limit_gb?: number | null;
          storage_used_bytes?: number;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          trial_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_name?: string;
          video_renders_limit?: number | null;
          video_renders_used?: number;
          storage_limit_gb?: number | null;
          storage_used_bytes?: number;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          trial_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      render_jobs: {
        Row: {
          id: string;
          project_id: string;
          render_type: string;
          status: string;
          progress_percent: number;
          settings: Json;
          output_url: string | null;
          output_file_size: number | null;
          subtitle_url: string | null;
          error_message: string | null;
          error_details: Json | null;
          started_at: string | null;
          completed_at: string | null;
          worker_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          render_type?: string;
          status?: string;
          progress_percent?: number;
          settings?: Json;
          output_url?: string | null;
          output_file_size?: number | null;
          subtitle_url?: string | null;
          error_message?: string | null;
          error_details?: Json | null;
          started_at?: string | null;
          completed_at?: string | null;
          worker_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          render_type?: string;
          status?: string;
          progress_percent?: number;
          settings?: Json;
          output_url?: string | null;
          output_file_size?: number | null;
          subtitle_url?: string | null;
          error_message?: string | null;
          error_details?: Json | null;
          started_at?: string | null;
          completed_at?: string | null;
          worker_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      media_assets: {
        Row: {
          id: string;
          organization_id: string;
          project_id: string | null;
          filename: string;
          file_type: string;
          mime_type: string;
          file_size_bytes: number;
          storage_key: string;
          storage_url: string;
          thumbnail_url: string | null;
          category: string | null;
          width: number | null;
          height: number | null;
          duration_seconds: number | null;
          ai_description: string | null;
          ai_tags: string[] | null;
          ai_quality_score: number | null;
          processing_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          project_id?: string | null;
          filename: string;
          file_type: string;
          mime_type: string;
          file_size_bytes: number;
          storage_key: string;
          storage_url: string;
          thumbnail_url?: string | null;
          category?: string | null;
          width?: number | null;
          height?: number | null;
          duration_seconds?: number | null;
          ai_description?: string | null;
          ai_tags?: string[] | null;
          ai_quality_score?: number | null;
          processing_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          project_id?: string | null;
          filename?: string;
          file_type?: string;
          mime_type?: string;
          file_size_bytes?: number;
          storage_key?: string;
          storage_url?: string;
          thumbnail_url?: string | null;
          category?: string | null;
          width?: number | null;
          height?: number | null;
          duration_seconds?: number | null;
          ai_description?: string | null;
          ai_tags?: string[] | null;
          ai_quality_score?: number | null;
          processing_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
